function [fitresult, gof] = createFit_double_exp(xaxis, OffHist_norm)
%CREATEFIT(XAXIS,OFFHIST_NORM)
%  Create a fit.
%
%  Data for 'double exp fit 1' fit:
%      X Input : xaxis
%      Y Output: OffHist_norm
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 22-Jul-2022 19:24:45


%% Fit: 'double exp fit 1'.
[xData, yData] = prepareCurveData( xaxis, OffHist_norm );

% Set up fittype and options.
ft = fittype( 'exp2' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = [0.19238409369875 -0.0406147549707358 0.00866468683220892 -0.0227979842763637];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Create a figure for the plots.
figure( 'Name', 'double exp fit 1' );

% Plot fit with data.
subplot( 2, 1, 1 );
h = plot( fitresult, xData, yData );
legend( h, 'OffHist_norm vs. xaxis', 'double exp fit 1', 'Location', 'NorthEast' );
set (gca, 'Yscale', 'log')
% Label axes
xlabel('\xi [\mum]','FontSize',14);
ylabel('P(\xi)','FontSize',14);
grid on

% Plot residuals.
subplot( 2, 1, 2 );
h = plot( fitresult, xData, yData, 'residuals' );
legend( h, 'double exp fit 1 - residuals', 'Zero Line', 'Location', 'NorthEast' );
% Label axes
xlabel('\xi [\mum]','FontSize',14);
ylabel('P(\xi)','FontSize',14);
grid on


